language: c

dist: focal

compiler:
  - clang
  - gcc

addons:
  sonarcloud:
    organization: "dernasherbrezon-github"
    token:
      secure: "lJ1152uFoSshIWVfEpifeECbIEH3wA6YQXlCwjcqKFvn1lowaR4LcrHiHaLfR9b3gybKL2A12xBQqqPFAd6D8mJeMWulsc25fsQDyPW/ju16QhOCUvyyYF8IOJNm1uvXfd0Qcef6C8JNc0FsudrzSdkBA1fmgkgc1xK1sEe0wmvGZfGSXjxJqS8A7oCQ+dd7fJOSAmRxOBCgiauKbEs3p0teWsV90dDc55vnPOPx+2Wfp/aAOe/Uv07LRWuB8sGW+4GfVVd+6jdDz1F/m8WUZlpHEuSR6MVL1gpdtVvJMgm3W8WFMPjh9Fzbgkj952j8gD4Biz4c9B9/NJqmsTNQhtGDAVWTIVGYNytpwvP0CfS589NlNPr+iqwOW0LK8VjtKbBfN14Wl9chHR+6i2RYE0ccP+WaGrGNllVSOScnYJ4OeKeRH5hc4b4br/dsd8OVX/dBL/ct5CFzbUDILcnGHjdL/LSXyvhERgYMfYoRjQ5O7XFsftmfP6Ug8c4/KUzS23IKeAJqLutU1NZ6YDtjyH7j471mRY4za5nDGlxc/BImk0Cg3g7LQBsHZSeKP5w3evNCeNi2FkkL3sQs0QYBztQsbxYrRbtBHDt6JchF0A1IrfpKynQ8G7QKOp96I8rCIMwC4CP0cLXVzDfJO5OcFZq8NzVa9S0MPTkSdlQeNCo="

before_install:
  - sudo apt-get install -yq --allow-downgrades libc6=2.31-0ubuntu9.2 libc6-dev=2.31-0ubuntu9.2
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends --allow-downgrades --allow-remove-essential --allow-change-held-packages install libconfig-dev valgrind check cmake pkg-config libvolk2-dev -o Debug::pkgProblemResolver=yes

script:
  - set -e
  - if [[ $TRAVIS_COMPILER == 'gcc' ]]; then sh ./build_debug.sh; fi
  - mkdir release && cd release
  - cmake ..
  - make
