syntax = "proto3";

message gfsk_modem_settings {
    uint32 bandwidth = 1;
    uint32 baud_rate = 3;
    int64 deviation = 4;
    float bt = 5;
    bool use_dc_block = 6;
}

message psk_modem_settings {
    uint32 bandwidth = 1;
    uint32 baud_rate = 3;
    float rrc_beta = 4;
    uint32 rrc_delay = 5;
    float costas_bandwidth = 6;
    uint32 symsync_filter_bank_size = 7;
}

message psk_pm_modem_settings {
    uint32 baud_rate = 1;

    uint32 subcarrier_frequency = 3;
    float carrier_pll_bandwidth = 4;
    uint32 subcarrier_bandwidth = 5;

    float rrc_beta = 6;
    uint32 rrc_delay = 7;
    float costas_bandwidth = 8;
    uint32 symsync_filter_bank_size = 9;

    float modulation_index = 10;
}

message none_framing {
}

message ModemRequest {
    oneof modem_settings {
        gfsk_modem_settings gfsk = 1;
        psk_modem_settings bpsk = 2;
        psk_modem_settings dpsk = 3;
        psk_modem_settings sdpsk = 4;
        psk_pm_modem_settings psk_pm = 5;
    }
    oneof framing {
        none_framing none = 9;
    }
    uint64 sample_rate = 14;
    uint64 frequency = 15;
    uint64 syncword = 16;
    // 0 means no syncword used
    uint32 syncword_bits = 17;
}

enum response_status {
    SUCCESS = 0;
    FAILURE = 1;
}

message Response {
    response_status status = 1;
    uint32 details = 2;
}

message TxData {
    bytes data = 1;
}