syntax = "proto3";

message gmsk_modem_settings {
    uint64 center_freq = 1;
    uint64 sample_rate = 2;
    int64 offset = 3;
    uint32 baud_rate = 4;
    int64 deviation = 5;
    uint32 bandwidth = 6;
    float bt = 7;
    bool use_dc_block = 8;
}

message none_framing {
}

message RxRequest {
    oneof modem_settings {
        gmsk_modem_settings gmsk = 1;
    }
    oneof framing {
        none_framing none = 8;
    }
}

message TxRequest {
    oneof modem_settings {
        gmsk_modem_settings gmsk = 1;
    }
    oneof framing {
        none_framing none = 2;
    }
}

enum response_status {
    SUCCESS = 0;
    FAILURE = 1;
}

message Response {
    response_status status = 1;
    uint32 details = 2;
}

message TxData {
    bytes data = 1;
}