#!/bin/sh

set -e

# only these volk methods are being used
volk_profile -R volk_32f_x2_dot_prod_32f_a --path volk_32f_x2_dot_prod_32f_a
volk_profile -R volk_32fc_32f_dot_prod_32fc_a --path volk_32fc_32f_dot_prod_32fc_a
volk_profile -R volk_32f_sin_32f --path volk_32f_sin_32f
volk_profile -R volk_32f_cos_32f --path volk_32f_cos_32f
volk_profile -R volk_32f_s32f_convert_8i --path volk_32f_s32f_convert_8i
volk_profile -R volk_32fc_x2_multiply_conjugate_32fc --path volk_32fc_x2_multiply_conjugate_32fc
volk_profile -R volk_32fc_x2_multiply_32fc --path volk_32fc_x2_multiply_32fc
volk_profile -R volk_32f_s32f_convert_16i --path volk_32f_s32f_convert_16i
volk_profile -R volk_16i_s32f_convert_32f --path volk_16i_s32f_convert_32f

mkdir -p /etc/sdr-modem/volk
cat volk_32f_x2_dot_prod_32f_a/volk_config volk_16i_s32f_convert_32f/volk_config volk_32f_s32f_convert_16i/volk_config volk_32fc_x2_multiply_32fc/volk_config volk_32fc_x2_multiply_conjugate_32fc/volk_config volk_32fc_32f_dot_prod_32fc_a/volk_config volk_32f_sin_32f/volk_config volk_32f_cos_32f/volk_config volk_32f_s32f_convert_8i/volk_config > /etc/sdr-modem/volk/volk_config

# remove unused dirs
rm -r volk_32f_x2_dot_prod_32f_a volk_16i_s32f_convert_32f volk_32f_s32f_convert_16i volk_32fc_x2_multiply_32fc volk_32fc_32f_dot_prod_32fc_a volk_32f_sin_32f volk_32f_cos_32f volk_32f_s32f_convert_8i volk_32fc_x2_multiply_conjugate_32fc

#DEBHELPER#