/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: api.proto */

#ifndef PROTOBUF_C_api_2eproto__INCLUDED
#define PROTOBUF_C_api_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct GfskModemSettings GfskModemSettings;
typedef struct NoneFraming NoneFraming;
typedef struct ModemRequest ModemRequest;
typedef struct Response Response;
typedef struct TxData TxData;


/* --- enums --- */

typedef enum _ResponseStatus {
  RESPONSE_STATUS__SUCCESS = 0,
  RESPONSE_STATUS__FAILURE = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(RESPONSE_STATUS)
} ResponseStatus;

/* --- messages --- */

struct  GfskModemSettings
{
  ProtobufCMessage base;
  uint64_t center_freq;
  uint64_t sample_rate;
  int64_t offset;
  uint32_t baud_rate;
  int64_t deviation;
  uint32_t bandwidth;
  float bt;
  protobuf_c_boolean use_dc_block;
};
#define GFSK_MODEM_SETTINGS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gfsk_modem_settings__descriptor) \
, 0, 0, 0, 0, 0, 0, 0, 0 }


struct  NoneFraming
{
  ProtobufCMessage base;
};
#define NONE_FRAMING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&none_framing__descriptor) \
 }


typedef enum {
  MODEM_REQUEST__MODEM_SETTINGS__NOT_SET = 0,
  MODEM_REQUEST__MODEM_SETTINGS_GFSK = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MODEM_REQUEST__MODEM_SETTINGS__CASE)
} ModemRequest__ModemSettingsCase;

typedef enum {
  MODEM_REQUEST__FRAMING__NOT_SET = 0,
  MODEM_REQUEST__FRAMING_NONE = 9
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MODEM_REQUEST__FRAMING__CASE)
} ModemRequest__FramingCase;

struct  ModemRequest
{
  ProtobufCMessage base;
  ModemRequest__ModemSettingsCase modem_settings_case;
  union {
    GfskModemSettings *gfsk;
  };
  ModemRequest__FramingCase framing_case;
  union {
    NoneFraming *none;
  };
};
#define MODEM_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&modem_request__descriptor) \
, MODEM_REQUEST__MODEM_SETTINGS__NOT_SET, {0}, MODEM_REQUEST__FRAMING__NOT_SET, {0} }


struct  Response
{
  ProtobufCMessage base;
  ResponseStatus status;
  uint32_t details;
};
#define RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&response__descriptor) \
, RESPONSE_STATUS__SUCCESS, 0 }


struct  TxData
{
  ProtobufCMessage base;
  ProtobufCBinaryData data;
};
#define TX_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&tx_data__descriptor) \
, {0,NULL} }


/* GfskModemSettings methods */
void   gfsk_modem_settings__init
                     (GfskModemSettings         *message);
size_t gfsk_modem_settings__get_packed_size
                     (const GfskModemSettings   *message);
size_t gfsk_modem_settings__pack
                     (const GfskModemSettings   *message,
                      uint8_t             *out);
size_t gfsk_modem_settings__pack_to_buffer
                     (const GfskModemSettings   *message,
                      ProtobufCBuffer     *buffer);
GfskModemSettings *
       gfsk_modem_settings__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gfsk_modem_settings__free_unpacked
                     (GfskModemSettings *message,
                      ProtobufCAllocator *allocator);
/* NoneFraming methods */
void   none_framing__init
                     (NoneFraming         *message);
size_t none_framing__get_packed_size
                     (const NoneFraming   *message);
size_t none_framing__pack
                     (const NoneFraming   *message,
                      uint8_t             *out);
size_t none_framing__pack_to_buffer
                     (const NoneFraming   *message,
                      ProtobufCBuffer     *buffer);
NoneFraming *
       none_framing__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   none_framing__free_unpacked
                     (NoneFraming *message,
                      ProtobufCAllocator *allocator);
/* ModemRequest methods */
void   modem_request__init
                     (ModemRequest         *message);
size_t modem_request__get_packed_size
                     (const ModemRequest   *message);
size_t modem_request__pack
                     (const ModemRequest   *message,
                      uint8_t             *out);
size_t modem_request__pack_to_buffer
                     (const ModemRequest   *message,
                      ProtobufCBuffer     *buffer);
ModemRequest *
       modem_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   modem_request__free_unpacked
                     (ModemRequest *message,
                      ProtobufCAllocator *allocator);
/* Response methods */
void   response__init
                     (Response         *message);
size_t response__get_packed_size
                     (const Response   *message);
size_t response__pack
                     (const Response   *message,
                      uint8_t             *out);
size_t response__pack_to_buffer
                     (const Response   *message,
                      ProtobufCBuffer     *buffer);
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator);
/* TxData methods */
void   tx_data__init
                     (TxData         *message);
size_t tx_data__get_packed_size
                     (const TxData   *message);
size_t tx_data__pack
                     (const TxData   *message,
                      uint8_t             *out);
size_t tx_data__pack_to_buffer
                     (const TxData   *message,
                      ProtobufCBuffer     *buffer);
TxData *
       tx_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   tx_data__free_unpacked
                     (TxData *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*GfskModemSettings_Closure)
                 (const GfskModemSettings *message,
                  void *closure_data);
typedef void (*NoneFraming_Closure)
                 (const NoneFraming *message,
                  void *closure_data);
typedef void (*ModemRequest_Closure)
                 (const ModemRequest *message,
                  void *closure_data);
typedef void (*Response_Closure)
                 (const Response *message,
                  void *closure_data);
typedef void (*TxData_Closure)
                 (const TxData *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    response_status__descriptor;
extern const ProtobufCMessageDescriptor gfsk_modem_settings__descriptor;
extern const ProtobufCMessageDescriptor none_framing__descriptor;
extern const ProtobufCMessageDescriptor modem_request__descriptor;
extern const ProtobufCMessageDescriptor response__descriptor;
extern const ProtobufCMessageDescriptor tx_data__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_api_2eproto__INCLUDED */
