/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: api.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "../api.pb-c.h"
void   gfsk_modem_settings__init
                     (GfskModemSettings         *message)
{
  static const GfskModemSettings init_value = GFSK_MODEM_SETTINGS__INIT;
  *message = init_value;
}
size_t gfsk_modem_settings__get_packed_size
                     (const GfskModemSettings *message)
{
  assert(message->base.descriptor == &gfsk_modem_settings__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gfsk_modem_settings__pack
                     (const GfskModemSettings *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gfsk_modem_settings__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gfsk_modem_settings__pack_to_buffer
                     (const GfskModemSettings *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gfsk_modem_settings__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GfskModemSettings *
       gfsk_modem_settings__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GfskModemSettings *)
     protobuf_c_message_unpack (&gfsk_modem_settings__descriptor,
                                allocator, len, data);
}
void   gfsk_modem_settings__free_unpacked
                     (GfskModemSettings *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gfsk_modem_settings__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   none_framing__init
                     (NoneFraming         *message)
{
  static const NoneFraming init_value = NONE_FRAMING__INIT;
  *message = init_value;
}
size_t none_framing__get_packed_size
                     (const NoneFraming *message)
{
  assert(message->base.descriptor == &none_framing__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t none_framing__pack
                     (const NoneFraming *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &none_framing__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t none_framing__pack_to_buffer
                     (const NoneFraming *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &none_framing__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NoneFraming *
       none_framing__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NoneFraming *)
     protobuf_c_message_unpack (&none_framing__descriptor,
                                allocator, len, data);
}
void   none_framing__free_unpacked
                     (NoneFraming *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &none_framing__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rx_request__init
                     (RxRequest         *message)
{
  static const RxRequest init_value = RX_REQUEST__INIT;
  *message = init_value;
}
size_t rx_request__get_packed_size
                     (const RxRequest *message)
{
  assert(message->base.descriptor == &rx_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rx_request__pack
                     (const RxRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rx_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rx_request__pack_to_buffer
                     (const RxRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rx_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RxRequest *
       rx_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RxRequest *)
     protobuf_c_message_unpack (&rx_request__descriptor,
                                allocator, len, data);
}
void   rx_request__free_unpacked
                     (RxRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rx_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tx_request__init
                     (TxRequest         *message)
{
  static const TxRequest init_value = TX_REQUEST__INIT;
  *message = init_value;
}
size_t tx_request__get_packed_size
                     (const TxRequest *message)
{
  assert(message->base.descriptor == &tx_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tx_request__pack
                     (const TxRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tx_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tx_request__pack_to_buffer
                     (const TxRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tx_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TxRequest *
       tx_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TxRequest *)
     protobuf_c_message_unpack (&tx_request__descriptor,
                                allocator, len, data);
}
void   tx_request__free_unpacked
                     (TxRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tx_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response__init
                     (Response         *message)
{
  static const Response init_value = RESPONSE__INIT;
  *message = init_value;
}
size_t response__get_packed_size
                     (const Response *message)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response__pack
                     (const Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response__pack_to_buffer
                     (const Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Response *)
     protobuf_c_message_unpack (&response__descriptor,
                                allocator, len, data);
}
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tx_data__init
                     (TxData         *message)
{
  static const TxData init_value = TX_DATA__INIT;
  *message = init_value;
}
size_t tx_data__get_packed_size
                     (const TxData *message)
{
  assert(message->base.descriptor == &tx_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tx_data__pack
                     (const TxData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tx_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tx_data__pack_to_buffer
                     (const TxData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tx_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TxData *
       tx_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TxData *)
     protobuf_c_message_unpack (&tx_data__descriptor,
                                allocator, len, data);
}
void   tx_data__free_unpacked
                     (TxData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tx_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor gfsk_modem_settings__field_descriptors[8] =
{
  {
    "center_freq",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(GfskModemSettings, center_freq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sample_rate",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(GfskModemSettings, sample_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(GfskModemSettings, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "baud_rate",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GfskModemSettings, baud_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviation",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(GfskModemSettings, deviation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bandwidth",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GfskModemSettings, bandwidth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bt",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(GfskModemSettings, bt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "use_dc_block",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(GfskModemSettings, use_dc_block),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gfsk_modem_settings__field_indices_by_name[] = {
  5,   /* field[5] = bandwidth */
  3,   /* field[3] = baud_rate */
  6,   /* field[6] = bt */
  0,   /* field[0] = center_freq */
  4,   /* field[4] = deviation */
  2,   /* field[2] = offset */
  1,   /* field[1] = sample_rate */
  7,   /* field[7] = use_dc_block */
};
static const ProtobufCIntRange gfsk_modem_settings__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor gfsk_modem_settings__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gfsk_modem_settings",
  "GfskModemSettings",
  "GfskModemSettings",
  "",
  sizeof(GfskModemSettings),
  8,
  gfsk_modem_settings__field_descriptors,
  gfsk_modem_settings__field_indices_by_name,
  1,  gfsk_modem_settings__number_ranges,
  (ProtobufCMessageInit) gfsk_modem_settings__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define none_framing__field_descriptors NULL
#define none_framing__field_indices_by_name NULL
#define none_framing__number_ranges NULL
const ProtobufCMessageDescriptor none_framing__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "none_framing",
  "NoneFraming",
  "NoneFraming",
  "",
  sizeof(NoneFraming),
  0,
  none_framing__field_descriptors,
  none_framing__field_indices_by_name,
  0,  none_framing__number_ranges,
  (ProtobufCMessageInit) none_framing__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rx_request__field_descriptors[2] =
{
  {
    "gfsk",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RxRequest, modem_settings_case),
    offsetof(RxRequest, gfsk),
    &gfsk_modem_settings__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "none",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RxRequest, framing_case),
    offsetof(RxRequest, none),
    &none_framing__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rx_request__field_indices_by_name[] = {
  0,   /* field[0] = gfsk */
  1,   /* field[1] = none */
};
static const ProtobufCIntRange rx_request__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 9, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor rx_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RxRequest",
  "RxRequest",
  "RxRequest",
  "",
  sizeof(RxRequest),
  2,
  rx_request__field_descriptors,
  rx_request__field_indices_by_name,
  2,  rx_request__number_ranges,
  (ProtobufCMessageInit) rx_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tx_request__field_descriptors[2] =
{
  {
    "gfsk",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TxRequest, modem_settings_case),
    offsetof(TxRequest, gfsk),
    &gfsk_modem_settings__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "none",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(TxRequest, framing_case),
    offsetof(TxRequest, none),
    &none_framing__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tx_request__field_indices_by_name[] = {
  0,   /* field[0] = gfsk */
  1,   /* field[1] = none */
};
static const ProtobufCIntRange tx_request__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 9, 1 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor tx_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TxRequest",
  "TxRequest",
  "TxRequest",
  "",
  sizeof(TxRequest),
  2,
  tx_request__field_descriptors,
  tx_request__field_indices_by_name,
  2,  tx_request__number_ranges,
  (ProtobufCMessageInit) tx_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__field_descriptors[2] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Response, status),
    &response_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "details",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Response, details),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__field_indices_by_name[] = {
  1,   /* field[1] = details */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response",
  "Response",
  "Response",
  "",
  sizeof(Response),
  2,
  response__field_descriptors,
  response__field_indices_by_name,
  1,  response__number_ranges,
  (ProtobufCMessageInit) response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tx_data__field_descriptors[1] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(TxData, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tx_data__field_indices_by_name[] = {
  0,   /* field[0] = data */
};
static const ProtobufCIntRange tx_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor tx_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TxData",
  "TxData",
  "TxData",
  "",
  sizeof(TxData),
  1,
  tx_data__field_descriptors,
  tx_data__field_indices_by_name,
  1,  tx_data__number_ranges,
  (ProtobufCMessageInit) tx_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue response_status__enum_values_by_number[2] =
{
  { "SUCCESS", "RESPONSE_STATUS__SUCCESS", 0 },
  { "FAILURE", "RESPONSE_STATUS__FAILURE", 1 },
};
static const ProtobufCIntRange response_status__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex response_status__enum_values_by_name[2] =
{
  { "FAILURE", 1 },
  { "SUCCESS", 0 },
};
const ProtobufCEnumDescriptor response_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "response_status",
  "response_status",
  "ResponseStatus",
  "",
  2,
  response_status__enum_values_by_number,
  2,
  response_status__enum_values_by_name,
  1,
  response_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
