/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: api.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "api.pb-c.h"
void   gfsk_modem_settings__init
                     (GfskModemSettings         *message)
{
  static const GfskModemSettings init_value = GFSK_MODEM_SETTINGS__INIT;
  *message = init_value;
}
size_t gfsk_modem_settings__get_packed_size
                     (const GfskModemSettings *message)
{
  assert(message->base.descriptor == &gfsk_modem_settings__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gfsk_modem_settings__pack
                     (const GfskModemSettings *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gfsk_modem_settings__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gfsk_modem_settings__pack_to_buffer
                     (const GfskModemSettings *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gfsk_modem_settings__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
GfskModemSettings *
       gfsk_modem_settings__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (GfskModemSettings *)
     protobuf_c_message_unpack (&gfsk_modem_settings__descriptor,
                                allocator, len, data);
}
void   gfsk_modem_settings__free_unpacked
                     (GfskModemSettings *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gfsk_modem_settings__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bpsk_modem_settings__init
                     (BpskModemSettings         *message)
{
  static const BpskModemSettings init_value = BPSK_MODEM_SETTINGS__INIT;
  *message = init_value;
}
size_t bpsk_modem_settings__get_packed_size
                     (const BpskModemSettings *message)
{
  assert(message->base.descriptor == &bpsk_modem_settings__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bpsk_modem_settings__pack
                     (const BpskModemSettings *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bpsk_modem_settings__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bpsk_modem_settings__pack_to_buffer
                     (const BpskModemSettings *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bpsk_modem_settings__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BpskModemSettings *
       bpsk_modem_settings__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BpskModemSettings *)
     protobuf_c_message_unpack (&bpsk_modem_settings__descriptor,
                                allocator, len, data);
}
void   bpsk_modem_settings__free_unpacked
                     (BpskModemSettings *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &bpsk_modem_settings__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   none_framing__init
                     (NoneFraming         *message)
{
  static const NoneFraming init_value = NONE_FRAMING__INIT;
  *message = init_value;
}
size_t none_framing__get_packed_size
                     (const NoneFraming *message)
{
  assert(message->base.descriptor == &none_framing__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t none_framing__pack
                     (const NoneFraming *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &none_framing__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t none_framing__pack_to_buffer
                     (const NoneFraming *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &none_framing__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NoneFraming *
       none_framing__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NoneFraming *)
     protobuf_c_message_unpack (&none_framing__descriptor,
                                allocator, len, data);
}
void   none_framing__free_unpacked
                     (NoneFraming *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &none_framing__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   modem_request__init
                     (ModemRequest         *message)
{
  static const ModemRequest init_value = MODEM_REQUEST__INIT;
  *message = init_value;
}
size_t modem_request__get_packed_size
                     (const ModemRequest *message)
{
  assert(message->base.descriptor == &modem_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t modem_request__pack
                     (const ModemRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &modem_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t modem_request__pack_to_buffer
                     (const ModemRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &modem_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ModemRequest *
       modem_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ModemRequest *)
     protobuf_c_message_unpack (&modem_request__descriptor,
                                allocator, len, data);
}
void   modem_request__free_unpacked
                     (ModemRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &modem_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   response__init
                     (Response         *message)
{
  static const Response init_value = RESPONSE__INIT;
  *message = init_value;
}
size_t response__get_packed_size
                     (const Response *message)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t response__pack
                     (const Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t response__pack_to_buffer
                     (const Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Response *
       response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Response *)
     protobuf_c_message_unpack (&response__descriptor,
                                allocator, len, data);
}
void   response__free_unpacked
                     (Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   tx_data__init
                     (TxData         *message)
{
  static const TxData init_value = TX_DATA__INIT;
  *message = init_value;
}
size_t tx_data__get_packed_size
                     (const TxData *message)
{
  assert(message->base.descriptor == &tx_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t tx_data__pack
                     (const TxData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &tx_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t tx_data__pack_to_buffer
                     (const TxData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &tx_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TxData *
       tx_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TxData *)
     protobuf_c_message_unpack (&tx_data__descriptor,
                                allocator, len, data);
}
void   tx_data__free_unpacked
                     (TxData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &tx_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor gfsk_modem_settings__field_descriptors[7] =
{
  {
    "center_freq",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(GfskModemSettings, center_freq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sample_rate",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(GfskModemSettings, sample_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "baud_rate",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GfskModemSettings, baud_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviation",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(GfskModemSettings, deviation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bandwidth",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(GfskModemSettings, bandwidth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bt",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(GfskModemSettings, bt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "use_dc_block",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(GfskModemSettings, use_dc_block),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gfsk_modem_settings__field_indices_by_name[] = {
  4,   /* field[4] = bandwidth */
  2,   /* field[2] = baud_rate */
  5,   /* field[5] = bt */
  0,   /* field[0] = center_freq */
  3,   /* field[3] = deviation */
  1,   /* field[1] = sample_rate */
  6,   /* field[6] = use_dc_block */
};
static const ProtobufCIntRange gfsk_modem_settings__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 4, 2 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor gfsk_modem_settings__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gfsk_modem_settings",
  "GfskModemSettings",
  "GfskModemSettings",
  "",
  sizeof(GfskModemSettings),
  7,
  gfsk_modem_settings__field_descriptors,
  gfsk_modem_settings__field_indices_by_name,
  2,  gfsk_modem_settings__number_ranges,
  (ProtobufCMessageInit) gfsk_modem_settings__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bpsk_modem_settings__field_descriptors[7] =
{
  {
    "center_freq",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(BpskModemSettings, center_freq),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sample_rate",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(BpskModemSettings, sample_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "baud_rate",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BpskModemSettings, baud_rate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rrc_beta",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BpskModemSettings, rrc_beta),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rrc_delay",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BpskModemSettings, rrc_delay),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "costas_bandwidth",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(BpskModemSettings, costas_bandwidth),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "symsync_filter_bank_size",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(BpskModemSettings, symsync_filter_bank_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bpsk_modem_settings__field_indices_by_name[] = {
  2,   /* field[2] = baud_rate */
  0,   /* field[0] = center_freq */
  5,   /* field[5] = costas_bandwidth */
  3,   /* field[3] = rrc_beta */
  4,   /* field[4] = rrc_delay */
  1,   /* field[1] = sample_rate */
  6,   /* field[6] = symsync_filter_bank_size */
};
static const ProtobufCIntRange bpsk_modem_settings__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 4, 2 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor bpsk_modem_settings__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "bpsk_modem_settings",
  "BpskModemSettings",
  "BpskModemSettings",
  "",
  sizeof(BpskModemSettings),
  7,
  bpsk_modem_settings__field_descriptors,
  bpsk_modem_settings__field_indices_by_name,
  2,  bpsk_modem_settings__number_ranges,
  (ProtobufCMessageInit) bpsk_modem_settings__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define none_framing__field_descriptors NULL
#define none_framing__field_indices_by_name NULL
#define none_framing__number_ranges NULL
const ProtobufCMessageDescriptor none_framing__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "none_framing",
  "NoneFraming",
  "NoneFraming",
  "",
  sizeof(NoneFraming),
  0,
  none_framing__field_descriptors,
  none_framing__field_indices_by_name,
  0,  none_framing__number_ranges,
  (ProtobufCMessageInit) none_framing__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor modem_request__field_descriptors[5] =
{
  {
    "gfsk",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ModemRequest, modem_settings_case),
    offsetof(ModemRequest, gfsk),
    &gfsk_modem_settings__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bpsk",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ModemRequest, modem_settings_case),
    offsetof(ModemRequest, bpsk),
    &bpsk_modem_settings__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dpsk",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ModemRequest, modem_settings_case),
    offsetof(ModemRequest, dpsk),
    &bpsk_modem_settings__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sdpsk",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ModemRequest, modem_settings_case),
    offsetof(ModemRequest, sdpsk),
    &bpsk_modem_settings__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "none",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ModemRequest, framing_case),
    offsetof(ModemRequest, none),
    &none_framing__descriptor,
    NULL,
    PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned modem_request__field_indices_by_name[] = {
  1,   /* field[1] = bpsk */
  2,   /* field[2] = dpsk */
  0,   /* field[0] = gfsk */
  4,   /* field[4] = none */
  3,   /* field[3] = sdpsk */
};
static const ProtobufCIntRange modem_request__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 9, 4 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor modem_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ModemRequest",
  "ModemRequest",
  "ModemRequest",
  "",
  sizeof(ModemRequest),
  5,
  modem_request__field_descriptors,
  modem_request__field_indices_by_name,
  2,  modem_request__number_ranges,
  (ProtobufCMessageInit) modem_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor response__field_descriptors[2] =
{
  {
    "status",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Response, status),
    &response_status__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "details",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Response, details),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned response__field_indices_by_name[] = {
  1,   /* field[1] = details */
  0,   /* field[0] = status */
};
static const ProtobufCIntRange response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Response",
  "Response",
  "Response",
  "",
  sizeof(Response),
  2,
  response__field_descriptors,
  response__field_indices_by_name,
  1,  response__number_ranges,
  (ProtobufCMessageInit) response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor tx_data__field_descriptors[1] =
{
  {
    "data",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(TxData, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned tx_data__field_indices_by_name[] = {
  0,   /* field[0] = data */
};
static const ProtobufCIntRange tx_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor tx_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "TxData",
  "TxData",
  "TxData",
  "",
  sizeof(TxData),
  1,
  tx_data__field_descriptors,
  tx_data__field_indices_by_name,
  1,  tx_data__number_ranges,
  (ProtobufCMessageInit) tx_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue response_status__enum_values_by_number[2] =
{
  { "SUCCESS", "RESPONSE_STATUS__SUCCESS", 0 },
  { "FAILURE", "RESPONSE_STATUS__FAILURE", 1 },
};
static const ProtobufCIntRange response_status__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex response_status__enum_values_by_name[2] =
{
  { "FAILURE", 1 },
  { "SUCCESS", 0 },
};
const ProtobufCEnumDescriptor response_status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "response_status",
  "response_status",
  "ResponseStatus",
  "",
  2,
  response_status__enum_values_by_number,
  2,
  response_status__enum_values_by_name,
  1,
  response_status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
